### ISSUE TITLE
Reacto 0.2.12 - Fatal

### ISSUE THREAD

**Issue by FDiskas** [eveningkid/reacto#79]
Intel® Core™ i5-4210M CPU @ 2.60GHz × 4 
Zorin OS 12.3 64-bit (Ubuntu based)
https://github.com/eveningkid/reacto/releases/download/v0.2.12/Reacto_0.2.12_amd64.deb
After instalation
```
Uncaught Error: /opt/Reacto/resources/app.asar.unpacked/node_modules/nodegit/build/Release/nodegit.node: invalid ELF header
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:173:20)
    at Object.Module._extensions..node (module.js:598:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:187:18)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/opt/Reacto/resources/app.asar/node_modules/nodegit/dist/nodegit.js:12:12)
    at Object.<anonymous> (/opt/Reacto/resources/app.asar/node_modules/nodegit/dist/nodegit.js:1145:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
```
![error](https://i.imgur.com/nbAxNXH.png)

**Comment by eveningkid** [comment]
Hey @FDiskas! Feels like using `node-git` raised some issues for some users (#78). 
I don't really have time to investigate this more at the moment, sorry. I remember that Atom is using the same library and ran into similar issues when they added it.
If you have time and will, you can also give it a look. Otherwise, this will come sooner or later!

**Comment by ph98** [comment]
same here ubuntu 18.04(64bit)

**Comment by FDiskas** [comment]
is it true that `sudo apt-get install clang` before release could fix that? https://github.com/eveningkid/reacto/issues/78#issuecomment-386016168

**Comment by eveningkid** [comment]
Thank you very much for your input @FDiskas. I'm sorry, I have no ubuntu running on my computer right now.

If you want to help with the issue, it's actually pretty quick to test. 
After cloning the github repo and installing everything, you can run the command you mentioned and only then try to generate a release using the `yarn run release` command.
Then, you just need to run the generated executable and see if it works.

Let me know if you manage to get it working!

**Comment by FDiskas** [comment]
@eveningkid Confirmed: After installed
```
sudo apt-get install clang build-essential libssl-dev libcurl4-openssl-dev
```
and `yarn run release`
I got [error](https://github.com/electron-userland/electron-builder/issues/1693#issuecomment-380408619)
I generated [new token](https://github.com/settings/tokens/new)

 and
```
export GH_TOKEN=****
```
 I got working build. Probably this command should be added in to release pipeline for debian.

Here is the [builded version](https://yadi.sk/d/FyZQXbAe3VwvVj)

**Comment by eveningkid** [comment]
Do you have any idea how to add this to the release pipeline? 
I don't really know where to put it inside the travis configuration.

**Comment by FDiskas** [comment]
I would try here
https://github.com/eveningkid/reacto/blob/f69c5dc2e15bd6a706e23034d51738c99e221cc8/.travis.yml#L53
to ad extra command :/
